apiVersion: v1
kind: ConfigMap
metadata:
  name: job-orchestrator-api-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://job-orchestrator-postgres-service:5432/job_orchestrator_db
  JOB_WORKER_ID: kube-worker-1